In [2]:
# Core scverse libraries
import scanpy as sc
import anndata as ad
import pandas as pd
import matplotlib.pyplot as plt
import scanpy.external as sce
import json

In [3]:
sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(
    dpi=300,
    facecolor="white",
    figsize=(10, 8),  # Adjust as needed
    fontsize=22
)
plt.rcParams['axes.grid'] = False

In [3]:
adata = sc.read_h5ad("/Users/takahiro/Desktop/project/Reha/snRNAseq_scanpy/adata/CM_Ctrl_6W.h5ad")

In [4]:
adata.obs["type"] = adata.obs["type"].map({"Ctrl":"Ctrl","Reha6W":"Ex","SED6W":"SED"})

In [118]:
sc.pl.highest_expr_genes(adata, n_top=20)

normalizing counts per cell
    finished (0:00:00)

In [119]:
# for figure
# Create a figure with subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Plotting the individual graphs
sc.pl.violin(adata, ['n_genes_by_counts'], groupby='sample', ax=axes[0], show=False)
sc.pl.violin(adata, ['total_counts'], groupby='sample', ax=axes[1], show=False)
sc.pl.violin(adata, ['pct_counts_mt'], groupby='sample', ax=axes[2], show=False)

# Adjusting layout
plt.tight_layout()

# Display the plot
plt.show()

In [120]:
sc.pl.violin(
    adata,
    ["pct_counts_mt"],
    jitter=0,
    multi_panel=True,
)

In [121]:
sc.pl.scatter(adata, x="total_counts", y="pct_counts_mt")
sc.pl.scatter(adata, x="total_counts", y="n_genes_by_counts")

In [122]:
adata.raw = adata.copy()

In [123]:
sc.pp.normalize_total(adata, target_sum=1e4)

normalizing counts per cell
    finished (0:00:00)

In [124]:
sc.pp.log1p(adata)

WARNING: adata.X seems to be already log-transformed.

In [125]:
sc.pp.highly_variable_genes(adata, n_top_genes=2000)

extracting highly variable genes
    finished (0:00:00)
--> added
    'highly_variable', boolean vector (adata.var)
    'means', float vector (adata.var)
    'dispersions', float vector (adata.var)
    'dispersions_norm', float vector (adata.var)

In [126]:
sc.pl.highly_variable_genes(adata)

In [127]:
sc.pp.regress_out(adata, ["total_counts", "pct_counts_mt"])

regressing out ['total_counts', 'pct_counts_mt']
    sparse input is densified and may lead to high memory use
    finished (0:02:59)

In [128]:
sc.pp.scale(adata, max_value=10)

In [129]:
sc.tl.pca(adata, svd_solver="arpack")

computing PCA
    with n_comps=50
    finished (0:01:01)

In [130]:
sc.pl.pca_variance_ratio(adata, log=True)

In [131]:
adata.write_h5ad("./adata/CM_Ctrl_6W_beforecuration_241025.h5ad")

In [13]:
adata = sc.read_h5ad("./adata/CM_Ctrl_6W_beforecuration_241025.h5ad")

# Over clustering

In [14]:
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=15)

computing neighbors
    using 'X_pca' with n_pcs = 15
    finished: added to `.uns['neighbors']`
    `.obsp['distances']`, distances for each pair of neighbors
    `.obsp['connectivities']`, weighted adjacency matrix (0:00:14)

In [15]:
sc.tl.umap(adata, spread=0.5, min_dist=0.5)

computing UMAP
    finished: added
    'X_umap', UMAP coordinates (adata.obsm)
    'umap', UMAP parameters (adata.uns) (0:00:05)

# Downstream

In [16]:
sc.pl.umap(adata, color=["type"], vmax=5)

In [17]:
sc.tl.leiden(adata, resolution=1)

running Leiden clustering

/var/folders/dh/5v73cjps0k72p3ltz6hhg22c0000gn/T/ipykernel_95060/1886685787.py:1: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(adata, resolution=1)

    finished: found 14 clusters and added
    'leiden', the cluster labels (adata.obs, categorical) (0:00:00)

In [18]:
sc.pl.umap(adata, color=["leiden"])

In [19]:
# for figure
# Create a figure with subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Plotting the individual graphs
sc.pl.violin(adata, ['n_genes_by_counts'], groupby='leiden', ax=axes[0], show=False)
sc.pl.violin(adata, ['total_counts'], groupby='leiden', ax=axes[1], show=False)
sc.pl.violin(adata, ['pct_counts_mt'], groupby='leiden', ax=axes[2], show=False)

# Adjusting layout
plt.tight_layout()

# Display the plot
plt.show()

In [20]:
sc.pl.dotplot(adata, [
  "Ttn", "Mybpc3", #CMs
  "Dcn", "Col1a1", "Postn", # FBs
  "Frmd3", "Dlc1", "Myh11", # SMCs
  "Pecam1", "Cdh5", "Vwf","Npr3", # Enforthelial, cardialcells
  "Ptprc", "Mrc1", "Cd163", # Macrophages
  "Cd3e","Skap1", "Cd79a", "Cd79b","Il7r", "Kit", # Tcell Bcell
  "Lmnb1","Slpi","Retnlg","S100a9", #Granulocytes
  "Nrxn1", "Nrxn3", "Upk3b","Msln","Gpc3", 
  "Plin1", "Xkr4", "Acta2","Ms4a1","Ncr1","Vtn","Colec11","Steap4","Kcnj8","Mmrn1","Flt4"
], groupby="leiden", vmax=4)

In [21]:
# cluster 12 13 low quality
adata = adata[~adata.obs["leiden"].isin(["11","12","13"])]

# Down stream

In [22]:
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=15)
sc.tl.umap(adata, spread=0.5, min_dist=0.5)

computing neighbors
    using 'X_pca' with n_pcs = 15
    finished: added to `.uns['neighbors']`
    `.obsp['distances']`, distances for each pair of neighbors
    `.obsp['connectivities']`, weighted adjacency matrix (0:00:03)
computing UMAP
    finished: added
    'X_umap', UMAP coordinates (adata.obsm)
    'umap', UMAP parameters (adata.uns) (0:00:05)

In [23]:
sc.tl.leiden(adata, resolution=0.2)

running Leiden clustering
    finished: found 3 clusters and added
    'leiden', the cluster labels (adata.obs, categorical) (0:00:00)

In [7]:
sc.settings.set_figure_params(figsize=(6, 6), dpi=100)
sc.pl.umap(adata, color=["type"], save="_CM_sample", title="Sample type")

WARNING: saving figure to file figures/umap_CM_sample.pdf

In [4]:
sc.settings.set_figure_params(figsize=(6, 6), dpi=100)
sc.pl.umap(adata, color=["leiden"],save="_CM_leiden")

WARNING: saving figure to file figures/umap_CM_leiden.pdf

In [16]:
import matplotlib.pyplot as plt
import pandas as pd

# 'type'と'leiden'ごとの集計を行い、割合を計算
type_leiden_counts = adata.obs.groupby(['type', 'leiden']).size().unstack(fill_value=0)
type_leiden_percentage = type_leiden_counts.div(type_leiden_counts.sum(axis=1), axis=0) * 100

# 積み上げ棒グラフの作成
type_leiden_percentage.plot(kind='bar', stacked=True, figsize=(5, 4))

# グラフのタイトルとラベルを設定
plt.title('Leiden Proportions per sample')
plt.xlabel('Type')
plt.ylabel('Percentage')

# 凡例を調整
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(False)
# グラフを表示
plt.tight_layout()
plt.show()

/var/folders/dh/5v73cjps0k72p3ltz6hhg22c0000gn/T/ipykernel_50392/2379516000.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  type_leiden_counts = adata.obs.groupby(['type', 'leiden']).size().unstack(fill_value=0)

In [191]:
# Obtain cluster-specific differentially expressed genes
sc.tl.rank_genes_groups(adata, groupby="leiden", method="wilcoxon")

ranking genes
WARNING: It seems you use rank_genes_groups on the raw count data. Please logarithmize your data before calling rank_genes_groups.
    finished: added to `.uns['rank_genes_groups']`
    'names', sorted np.recarray to be indexed by group ids
    'scores', sorted np.recarray to be indexed by group ids
    'logfoldchanges', sorted np.recarray to be indexed by group ids
    'pvals', sorted np.recarray to be indexed by group ids
    'pvals_adj', sorted np.recarray to be indexed by group ids (0:00:07)

In [192]:
sc.tl.dendrogram(adata,groupby="leiden")

    using 'X_pca' with n_pcs = 50
Storing dendrogram info using `.uns['dendrogram_leiden']`

In [193]:
sc.pl.rank_genes_groups_dotplot(
    adata, groupby="leiden", standard_scale="var", n_genes=15)

In [194]:
adata.write_h5ad("./adata/CM_Ctrl_6W_analysed.h5ad")

In [3]:
adata = sc.read_h5ad("./adata/CM_Ctrl_6W_analysed.h5ad")

In [14]:
sc.settings.set_figure_params(figsize=(6, 6), dpi=100)
sc.pl.umap(
    adata,
    color="leiden",
    palette=["#D55E00", "#ADD8E6", "#EFC000"],   # ここを変更
    save="_CM_leiden"
)

WARNING: saving figure to file figures/umap_CM_leiden.pdf

In [18]:
import matplotlib.pyplot as plt
import pandas as pd

type_leiden_counts = adata.obs.groupby(['type', 'leiden']).size().unstack(fill_value=0)
type_leiden_percentage = type_leiden_counts.div(type_leiden_counts.sum(axis=1), axis=0) * 100

colors = ["#D55E00", "#ADD8E6", "#EFC000"]

ax = type_leiden_percentage.plot(
    kind='bar',
    stacked=True,
    figsize=(5,4),
    color=colors
)

ax.set_xticklabels(["Ctrl","Ex","SED"], rotation=0)

plt.title('Leiden Proportions per sample')
plt.xlabel('Type')
plt.ylabel('Percentage')

plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(False)

plt.tight_layout()
plt.show()

/var/folders/dh/5v73cjps0k72p3ltz6hhg22c0000gn/T/ipykernel_20615/2901097539.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  type_leiden_counts = adata.obs.groupby(['type', 'leiden']).size().unstack(fill_value=0)

In [10]:
adata.obs["type"].value_counts()

type
Ctrl      3935
Reha6W    3897
SED6W     3033
Name: count, dtype: int64

In [8]:
adata_MI = adata[adata.obs["type"]!="Ctrl"]

In [9]:
adata_MI

View of AnnData object with n_obs × n_vars = 6930 × 24225
    obs: 'sample', 'type', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'doublet_score', 'predicted_doublet', 'leiden', 'cell_type'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'cell_type_colors', 'dendrogram_leiden', 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'scrublet', 'type_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [7]:
adata_MI.write_h5ad("./adata/CM_MI_Ctrl_6W_analysed.h5ad")

In [10]:
adata_MI = adata_MI.raw.to_adata().copy()

In [11]:
sc.pl.umap(adata_MI, color=["type","leiden"])

In [9]:
adata_MI.write_h5ad("./adata/CM_MI_Ctrl_6W_analysed_raw.h5ad")

# Intra sample comparison

In [5]:
adata = adata.raw.to_adata().copy()

In [29]:
adata.write_h5ad("./adata/CM_Ctrl_6W_analysed_raw.h5ad")

In [ ]:
adata = sc.read_h5ad("./adata/CM_Ctrl_6W_analysed_raw.h5ad")

In [6]:
sc.pp.normalize_total(adata, target_sum=1e4)

normalizing counts per cell
    finished (0:00:00)

In [7]:
sc.pp.log1p(adata)

WARNING: adata.X seems to be already log-transformed.

In [8]:
print(adata.X)

  (0, 8)	0.6971460289906608
  (0, 10)	0.8153723956594539
  (0, 12)	0.22474501009158065
  (0, 13)	1.8785601211511584
  (0, 14)	0.5630443504006988
  (0, 17)	1.0166875855805892
  (0, 20)	0.22474501009158065
  (0, 21)	1.0166875855805892
  (0, 25)	0.4081327830260533
  (0, 27)	0.4081327830260533
  (0, 33)	0.22474501009158065
  (0, 35)	0.5630443504006988
  (0, 40)	1.1841876155148705
  (0, 43)	1.3276153593428761
  (0, 44)	0.22474501009158065
  (0, 46)	0.9210874346710384
  (0, 53)	0.22474501009158065
  (0, 57)	0.22474501009158065
  (0, 59)	1.4530284127076585
  (0, 60)	0.22474501009158065
  (0, 61)	0.6971460289906608
  (0, 65)	0.4081327830260533
  (0, 66)	1.0166875855805892
  (0, 95)	0.4081327830260533
  (0, 98)	0.6971460289906608
  :	:
  (10864, 23764)	3.1493726191012272
  (10864, 23809)	3.1493726191012272
  (10864, 23816)	6.770256844367929
  (10864, 23833)	3.1493726191012272
  (10864, 23853)	3.1493726191012272
  (10864, 23881)	3.820847124762276
  (10864, 23895)	3.1493726191012272
  (10864, 23905)	3.1493726191012272
  (10864, 23910)	3.1493726191012272
  (10864, 23939)	3.1493726191012272
  (10864, 23964)	4.218982357120946
  (10864, 23973)	3.1493726191012272
  (10864, 24039)	3.1493726191012272
  (10864, 24045)	3.1493726191012272
  (10864, 24050)	3.1493726191012272
  (10864, 24069)	3.1493726191012272
  (10864, 24070)	3.1493726191012272
  (10864, 24087)	3.1493726191012272
  (10864, 24111)	3.1493726191012272
  (10864, 24112)	4.218982357120946
  (10864, 24114)	3.1493726191012272
  (10864, 24131)	3.820847124762276
  (10864, 24151)	3.1493726191012272
  (10864, 24173)	3.1493726191012272
  (10864, 24189)	3.1493726191012272

In [9]:
# Obtain cluster-specific differentially expressed gene
sc.tl.rank_genes_groups(adata, groupby="leiden",groups=("2","0"),reference="0", method="wilcoxon")

ranking genes
    finished: added to `.uns['rank_genes_groups']`
    'names', sorted np.recarray to be indexed by group ids
    'scores', sorted np.recarray to be indexed by group ids
    'logfoldchanges', sorted np.recarray to be indexed by group ids
    'pvals', sorted np.recarray to be indexed by group ids
    'pvals_adj', sorted np.recarray to be indexed by group ids (0:00:09)

In [10]:
# Extract rank genes groups data from adata
rank_genes_groups = adata.uns["rank_genes_groups"]

# Convert the data into a DataFrame
groups = rank_genes_groups['names'].dtype.names  # Get all group names
dfs = []

for group in groups:
    df = pd.DataFrame({
        'gene': rank_genes_groups['names'][group],
        'logfc': rank_genes_groups['logfoldchanges'][group],
        'pvals_adj': rank_genes_groups['pvals_adj'][group]
    })
    df['group'] = group  # Add group information to identify the cell type/cluster
    dfs.append(df)

# Concatenate all groups into a single DataFrame
DEG = pd.concat(dfs, ignore_index=True)

In [11]:
DEG_leiden = DEG

In [12]:
DEG_leiden.to_csv("./DEG_leiden_2vs0.csv")

In [ ]:
DEG = DEG.loc[DEG["pvals_adj"] < 0.1]
DEG_2 = DEG.loc[DEG["logfc"] > 0.25]
DEG_0 = DEG.loc[DEG["logfc"] < -0.25]

In [14]:
DEG_0["logfc"] = -DEG_0["logfc"]

/var/folders/dh/5v73cjps0k72p3ltz6hhg22c0000gn/T/ipykernel_16478/2729650585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DEG_0["logfc"] = -DEG_0["logfc"]

In [22]:
sc.settings.set_figure_params(
    dpi=300,
    facecolor="white",
    figsize=(10, 8),  # Adjust as needed
    fontsize=22
)

In [23]:
import matplotlib.pyplot as plt
import numpy as np
from adjustText import adjust_text

# Sort the DataFrame by logfc_6W in descending order
DEG_sorted = DEG_2.sort_values(by='pvals_adj', ascending=True)
DEG_sorted['neg_log_pvals_adj'] = -np.log10(DEG_sorted['pvals_adj'])



# Create the dot plot
plt.figure(figsize=(10, 8))
plt.scatter(range(len(DEG_sorted)), DEG_sorted['neg_log_pvals_adj'], color='blue', s=50)
plt.ylabel('-log10(Adjusted p-value)')
plt.xlabel('Genes (Index)')
plt.title('Rank Plot of -log10(Adjusted p-value)')

# Select the top 10 genes for annotation
top_5_genes = DEG_sorted.head(5)

# Add annotations for the top 5 genes
texts = []
for i, row in top_5_genes.iterrows():
    text = plt.text(i, row['neg_log_pvals_adj'], row['gene'], fontsize=24, color='black')
    texts.append(text)

# Adjust text to avoid overlap
adjust_text(texts, arrowprops=dict(arrowstyle='-', color='gray'))

# Set x-ticks to blank
plt.xticks([])

# Display the plot
plt.tight_layout()
plt.show()

# Enrichment analysis

In [25]:
import gseapy as gp
mouse = gp.get_library_name(organism='Mouse')
mouse

['ARCHS4_Cell-lines',
 'ARCHS4_IDG_Coexp',
 'ARCHS4_Kinases_Coexp',
 'ARCHS4_TFs_Coexp',
 'ARCHS4_Tissues',
 'Achilles_fitness_decrease',
 'Achilles_fitness_increase',
 'Aging_Perturbations_from_GEO_down',
 'Aging_Perturbations_from_GEO_up',
 'Allen_Brain_Atlas_10x_scRNA_2021',
 'Allen_Brain_Atlas_down',
 'Allen_Brain_Atlas_up',
 'Azimuth_2023',
 'Azimuth_Cell_Types_2021',
 'BioCarta_2013',
 'BioCarta_2015',
 'BioCarta_2016',
 'BioPlanet_2019',
 'BioPlex_2017',
 'CCLE_Proteomics_2020',
 'CM4AI_U2OS_Protein_Localization_Assemblies',
 'COMPARTMENTS_Curated_2025',
 'COMPARTMENTS_Experimental_2025',
 'CORUM',
 'COVID-19_Related_Gene_Sets',
 'COVID-19_Related_Gene_Sets_2021',
 'Cancer_Cell_Line_Encyclopedia',
 'Carcinogenome',
 'CellMarker_2024',
 'CellMarker_Augmented_2021',
 'ChEA_2013',
 'ChEA_2015',
 'ChEA_2016',
 'ChEA_2022',
 'Chromosome_Location',
 'Chromosome_Location_hg19',
 'ClinVar_2019',
 'ClinVar_2025',
 'DGIdb_Drug_Targets_2024',
 'DSigDB',
 'Data_Acquisition_Method_Most_Popular_Genes',
 'DepMap_CRISPR_GeneDependency_CellLines_2023',
 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019',
 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019',
 'Descartes_Cell_Types_and_Tissue_2021',
 'Diabetes_Perturbations_GEO_2022',
 'DisGeNET',
 'Disease_Perturbations_from_GEO_down',
 'Disease_Perturbations_from_GEO_up',
 'Disease_Signatures_from_GEO_down_2014',
 'Disease_Signatures_from_GEO_up_2014',
 'DrugMatrix',
 'Drug_Perturbations_from_GEO_2014',
 'Drug_Perturbations_from_GEO_down',
 'Drug_Perturbations_from_GEO_up',
 'ENCODE_Histone_Modifications_2013',
 'ENCODE_Histone_Modifications_2015',
 'ENCODE_TF_ChIP-seq_2014',
 'ENCODE_TF_ChIP-seq_2015',
 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X',
 'ESCAPE',
 'Elsevier_Pathway_Collection',
 'Enrichr_Libraries_Most_Popular_Genes',
 'Enrichr_Submissions_TF-Gene_Coocurrence',
 'Enrichr_Users_Contributed_Lists_2020',
 'Epigenomics_Roadmap_HM_ChIP-seq',
 'FANTOM6_lncRNA_KD_DEGs',
 'GO_Biological_Process_2021',
 'GO_Biological_Process_2023',
 'GO_Biological_Process_2025',
 'GO_Cellular_Component_2021',
 'GO_Cellular_Component_2023',
 'GO_Cellular_Component_2025',
 'GO_Molecular_Function_2021',
 'GO_Molecular_Function_2023',
 'GO_Molecular_Function_2025',
 'GTEx_Aging_Signatures_2021',
 'GTEx_Tissue_Expression_Down',
 'GTEx_Tissue_Expression_Up',
 'GTEx_Tissues_V8_2023',
 'GWAS_Catalog_2019',
 'GWAS_Catalog_2023',
 'GWAS_Catalog_2025',
 'GeDiPNet_2023',
 'GeneSigDB',
 'Gene_Perturbations_from_GEO_down',
 'Gene_Perturbations_from_GEO_up',
 'Genes_Associated_with_NIH_Grants',
 'Genome_Browser_PWMs',
 'GlyGen_Glycosylated_Proteins_2022',
 'HDSigDB_Human_2021',
 'HDSigDB_Mouse_2021',
 'HMDB_Metabolites',
 'HMS_LINCS_KinomeScan',
 'HomoloGene',
 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression',
 'HuBMAP_ASCTplusB_augmented_2022',
 'HumanCyc_2015',
 'HumanCyc_2016',
 'Human_Gene_Atlas',
 'Human_Phenotype_Ontology',
 'IDG_Drug_Targets_2022',
 'InterPro_Domains_2019',
 'JASPAR_PWM_Human_2025',
 'JASPAR_PWM_Mouse_2025',
 'Jensen_COMPARTMENTS',
 'Jensen_DISEASES',
 'Jensen_DISEASES_Curated_2025',
 'Jensen_DISEASES_Experimental_2025',
 'Jensen_TISSUES',
 'KEA_2013',
 'KEA_2015',
 'KEGG_2013',
 'KEGG_2015',
 'KEGG_2016',
 'KEGG_2019_Human',
 'KEGG_2019_Mouse',
 'KEGG_2021_Human',
 'KEGG_2026',
 'KOMP2_Mouse_Phenotypes_2022',
 'Kinase_Perturbations_from_GEO_down',
 'Kinase_Perturbations_from_GEO_up',
 'L1000_Kinase_and_GPCR_Perturbations_down',
 'L1000_Kinase_and_GPCR_Perturbations_up',
 'LINCS_L1000_CRISPR_KO_Consensus_Sigs',
 'LINCS_L1000_Chem_Pert_Consensus_Sigs',
 'LINCS_L1000_Chem_Pert_down',
 'LINCS_L1000_Chem_Pert_up',
 'LINCS_L1000_Ligand_Perturbations_down',
 'LINCS_L1000_Ligand_Perturbations_up',
 'Ligand_Perturbations_from_GEO_down',
 'Ligand_Perturbations_from_GEO_up',
 'MAGMA_Drugs_and_Diseases',
 'MAGNET_2023',
 'MCF7_Perturbations_from_GEO_down',
 'MCF7_Perturbations_from_GEO_up',
 'MGI_Mammalian_Phenotype_Level_4_2021',
 'MGI_Mammalian_Phenotype_Level_4_2024',
 'MSigDB_Computational',
 'MSigDB_Hallmark_2020',
 'MSigDB_Oncogenic_Signatures',
 'Metabolomics_Workbench_Metabolites_2022',
 'Microbe_Perturbations_from_GEO_down',
 'Microbe_Perturbations_from_GEO_up',
 'MoTrPAC_2023',
 'Mouse_Gene_Atlas',
 'NCI-60_Cancer_Cell_Lines',
 'NCI-Nature_2016',
 'NIBR_DRUGseq_2025_down',
 'NIBR_DRUGseq_2025_up',
 'NURSA_Human_Endogenous_Complexome',
 'OMIM_Disease',
 'OMIM_Expanded',
 'Old_CMAP_down',
 'Old_CMAP_up',
 'Orphanet_Augmented_2021',
 'PFOCR_Pathways_2023',
 'PPI_Hub_Proteins',
 'PanglaoDB_Augmented_2021',
 'Panther_2015',
 'Panther_2016',
 'PerturbAtlas',
 'PerturbAtlas_MouseGenePerturbationSigs',
 'PerturbSeq_ReplogleK562',
 'PerturbSeq_ReplogleRPE1',
 'Pfam_Domains_2019',
 'Pfam_InterPro_Domains',
 'PheWeb_2019',
 'PhenGenI_Association_2021',
 'Phosphatase_Substrates_from_DEPOD',
 'ProteomicsDB_2020',
 'Proteomics_Drug_Atlas_2023',
 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO',
 'Rare_Diseases_AutoRIF_ARCHS4_Predictions',
 'Rare_Diseases_AutoRIF_Gene_Lists',
 'Rare_Diseases_GeneRIF_ARCHS4_Predictions',
 'Rare_Diseases_GeneRIF_Gene_Lists',
 'Reactome_2022',
 'Reactome_Pathways_2024',
 'RummaGEO_DrugPerturbations_2025',
 'RummaGEO_GenePerturbations_2025',
 'Rummagene_kinases',
 'Rummagene_signatures',
 'Rummagene_transcription_factors',
 'SILAC_Phosphoproteomics',
 'Sciplex_Drug_Perturbation_Signatures_2025',
 'SubCell_BarCode',
 'SynGO_2022',
 'SynGO_2024',
 'SysMyo_Muscle_Gene_Sets',
 'TF-LOF_Expression_from_GEO',
 'TF_Perturbations_Followed_by_Expression',
 'TG_GATES_2020',
 'TISSUES_Curated_2025',
 'TISSUES_Experimental_2025',
 'TRANSFAC_and_JASPAR_PWMs',
 'TRRUST_Transcription_Factors_2019',
 'Table_Mining_of_CRISPR_Studies',
 'Tabula_Muris',
 'Tabula_Sapiens',
 'TargetScan_microRNA',
 'TargetScan_microRNA_2017',
 'The_Kinase_Library_2023',
 'The_Kinase_Library_2024',
 'Tissue_Protein_Expression_from_Human_Proteome_Map',
 'Tissue_Protein_Expression_from_ProteomicsDB',
 'Transcription_Factor_PPIs',
 'UK_Biobank_GWAS_v1',
 'Virus-Host_PPI_P-HIPSTer_2020',
 'VirusMINT',
 'Virus_Perturbations_from_GEO_down',
 'Virus_Perturbations_from_GEO_up',
 'WikiPathway_2021_Human',
 'WikiPathway_2023_Human',
 'WikiPathways_2013',
 'WikiPathways_2015',
 'WikiPathways_2016',
 'WikiPathways_2019_Human',
 'WikiPathways_2019_Mouse',
 'WikiPathways_2024_Human',
 'WikiPathways_2024_Mouse',
 'dbGaP',
 'huMAP',
 'lncHUB_lncRNA_Co-Expression',
 'miRTarBase_2017']

## Cluster 2 DEG

In [36]:
up_genes = DEG_2["gene"]
up_genes = up_genes.squeeze().str.strip().to_list()

In [37]:
geneset_list = ['MSigDB_Hallmark_2020','GO_Biological_Process_2023','KEGG_2019_Mouse','Reactome_2022']
enr = gp.enrichr(gene_list=up_genes,
                 gene_sets=geneset_list,
                 organism='mouse', # don't forget to set organism to the one you desired! e.g. Yeast
                 outdir=None, # don't write to disk
                )
enr.results['n_genes'] = [int(x.split('/')[0]) for x in enr.results['Overlap']]

metrics_to_sort = '-log10(adjusted P-value)'
for geneset in geneset_list:
    print(geneset)
    df = enr.results[enr.results['Gene_set'] == geneset]
    df = df[df['Adjusted P-value'] < 0.05]
    df["-log10(adjusted P-value)"] = -np.log10(df['Adjusted P-value'])
    df = df.sort_values(metrics_to_sort,ascending=False)
    display(df[:30])
    
    # plot
    n_rank = 10
    plt.rcParams['axes.grid'] = False
    plt.rcParams['figure.figsize'] = 8,6
    plt.barh(width=df[:n_rank][metrics_to_sort],
             y=[x.split(' (')[0] for x in df[:n_rank]['Term']],
             color='darkred')
    plt.gca().invert_yaxis()
    plt.xlabel(metrics_to_sort)
    plt.title(f'{geneset}')
    plt.margins(y=0.02)
    plt.show()

## Cluster 0 DEG

In [39]:
up_genes = DEG_0["gene"]
up_genes = up_genes.squeeze().str.strip().to_list()

In [40]:
geneset_list = ['MSigDB_Hallmark_2020','GO_Biological_Process_2023','KEGG_2019_Mouse','Reactome_2022']
enr = gp.enrichr(gene_list=up_genes,
                 gene_sets=geneset_list,
                 organism='mouse', # don't forget to set organism to the one you desired! e.g. Yeast
                 outdir="CM_cluster0_DEG.csv", # don't write to disk
                )
enr.results['n_genes'] = [int(x.split('/')[0]) for x in enr.results['Overlap']]

/Users/takahiro/miniforge3/envs/scanpy/lib/python3.10/site-packages/gseapy/plot.py:694: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df[self.colname].replace(
/Users/takahiro/miniforge3/envs/scanpy/lib/python3.10/site-packages/gseapy/plot.py:694: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df[self.colname].replace(
/Users/takahiro/miniforge3/envs/scanpy/lib/python3.10/site-packages/gseapy/plot.py:694: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df[self.colname].replace(
/Users/takahiro/miniforge3/envs/scanpy/lib/python3.10/site-packages/gseapy/plot.py:694: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df[self.colname].replace(

In [41]:
metrics_to_sort = '-log10(adjusted P-value)'
for geneset in geneset_list:
    print(geneset)
    df = enr.results[enr.results['Gene_set'] == geneset]
    df = df[df['Adjusted P-value'] < 0.05]
    df["-log10(adjusted P-value)"] = -np.log10(df['Adjusted P-value'])
    df = df.sort_values(metrics_to_sort,ascending=False)
    display(df[:30])
    
    # plot
    n_rank = 10
    plt.rcParams['axes.grid'] = False
    plt.rcParams['figure.figsize'] = 8,6
    plt.barh(width=df[:n_rank][metrics_to_sort],
             y=[x.split(' (')[0] for x in df[:n_rank]['Term']],
             color='darkred')
    plt.gca().invert_yaxis()
    plt.xlabel(metrics_to_sort)
    plt.title(f'{geneset}')
    plt.margins(y=0.02)
    plt.show()

MSigDB_Hallmark_2020

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,n_genes,-log10(adjusted P-value)
0,MSigDB_Hallmark_2020,UV Response Dn,49/144,4.635293e-16,2.317647e-14,0,0,5.020165,177.250289,PHF3;CITED2;CELF2;SCHIP1;SERPINE1;PTEN;PTPRM;P...,49,13.634953
1,MSigDB_Hallmark_2020,Mitotic Spindle,49/199,3.165197e-10,7.912993e-09,0,0,3.169726,69.333434,DOCK4;TRIO;WASL;SMC3;ARHGAP5;AKAP13;PCM1;OPHN1...,49,8.101659
2,MSigDB_Hallmark_2020,Myogenesis,45/200,3.243509e-08,4.054386e-07,0,0,2.810210,48.459329,EIF4A2;RB1;ITGB1;MYOM1;ITGB5;FLII;SCHIP1;FHL1;...,45,6.392075
3,MSigDB_Hallmark_2020,heme Metabolism,45/200,3.243509e-08,4.054386e-07,0,0,2.810210,48.459329,SLC22A4;USP15;GYPC;MGST3;NR3C1;CLCN3;ADD1;TRAK...,45,6.392075
4,MSigDB_Hallmark_2020,TGF-beta Signaling,19/54,2.416757e-07,2.416757e-06,0,0,5.216626,79.478790,ACVR1;SMAD1;WWTR1;BMPR2;SMURF2;IFNGR2;SERPINE1...,19,5.616767
5,MSigDB_Hallmark_2020,PI3K/AKT/mTOR Signaling,24/105,3.796177e-05,3.163480e-04,0,0,2.847605,28.985574,ATF1;SMAD2;ACTR3;GSK3B;ACTR2;PRKAA2;CAB39;CAB3...,24,3.499835
6,MSigDB_Hallmark_2020,Hypoxia,32/200,2.337202e-03,1.669430e-02,0,0,1.829571,11.085008,CITED2;GBE1;SERPINE1;NEDD4L;PYGM;RORA;VLDLR;NR...,32,1.777432
7,MSigDB_Hallmark_2020,Androgen Response,18/100,5.845972e-03,3.653732e-02,0,0,2.102812,10.812667,B4GALT1;TSC22D1;HOMER2;GSR;ARID5B;PTPN21;RPS6K...,18,1.437263
8,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,30/199,7.492103e-03,4.162279e-02,0,0,1.703154,8.335076,CYFIP1;PHTF2;BMPR2;CSF1;RORA;IKZF2;HK2;IGF1R;N...,30,1.380669
9,MSigDB_Hallmark_2020,Protein Secretion,17/96,8.556885e-03,4.278443e-02,0,0,2.060655,9.810816,RAB2A;VPS4B;SNAP23;ADAM10;AP2B1;CLCN3;IGF2R;TO...,17,1.368714

GO_Biological_Process_2023

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,n_genes,-log10(adjusted P-value)
50,GO_Biological_Process_2023,Protein Phosphorylation (GO:0006468),102/500,6.262357e-14,2.508074e-10,0,0,2.524736,76.756087,ATF2;IGF1R;RPS6KA3;PPP4R1;PDK4;MAP3K7;PDK1;ACV...,102,9.600660
51,GO_Biological_Process_2023,Protein Modification Process (GO:0036211),130/711,1.323309e-13,2.649926e-10,0,0,2.216019,65.712656,UBE2D3;ARAF;PLOD2;PPP2R2A;PARK7;PPP4R1;PDK4;LA...,130,9.576766
52,GO_Biological_Process_2023,Phosphorylation (GO:0016310),86/429,1.585684e-11,2.116888e-08,0,0,2.455843,61.070477,GSK3B;SMG1;DGKD;BMPR2;MAST2;PIK3CB;LIMD1;HK2;R...,86,7.674302
53,GO_Biological_Process_2023,Actomyosin Structure Organization (GO:0031032),28/77,1.484164e-10,1.486020e-07,0,0,5.513324,124.772022,FHOD3;ITGB1;ITGB5;ROCK1;FLII;LMOD3;MYOM2;LMOD2...,28,6.827975
54,GO_Biological_Process_2023,Protein Ubiquitination (GO:0016567),83/434,4.131970e-10,3.309708e-07,0,0,2.311285,49.940157,TRIM72;DET1;RNF13;UBE3C;FBH1;UBE2D3;UBE2D1;PRP...,83,6.480210
55,GO_Biological_Process_2023,Positive Regulation Of DNA-templated Transcrip...,182/1243,1.225487e-09,8.180126e-07,0,0,1.702375,34.932617,ATF1;ATF2;CCNT2;CRTC3;ICE1;KDM1A;HNRNPU;RORA;P...,182,6.087240
56,GO_Biological_Process_2023,Ubiquitin-Dependent Protein Catabolic Process ...,71/367,4.594447e-09,2.628680e-06,0,0,2.336321,44.853657,GSK3B;TRIM72;UBE3C;RNF13;USP33;UBE2D3;OTUD7B;U...,71,5.580262
57,GO_Biological_Process_2023,Positive Regulation Of Transcription By RNA Po...,141/938,1.977386e-08,9.899290e-06,0,0,1.741359,30.889810,ATF1;ATF2;CCNT2;CRTC3;KDM1A;ZMYND8;HNRNPU;RORA...,141,5.004396
58,GO_Biological_Process_2023,Peptidyl-Serine Phosphorylation (GO:0018105),38/158,5.881537e-08,2.617284e-05,0,0,3.059636,50.939466,GSK3B;SMG1;CAMK2D;CAB39;ROCK1;TNKS;MAST2;RPS6K...,38,4.582149
59,GO_Biological_Process_2023,Myofibril Assembly (GO:0030239),18/46,7.607652e-08,3.046865e-05,0,0,6.176692,101.245404,FHOD3;TMOD1;ADPRHL1;ACTN2;FLII;LMOD3;MYOM2;KLH...,18,4.516147
60,GO_Biological_Process_2023,Protein Modification By Small Protein Conjugat...,66/364,2.049649e-07,7.462585e-05,0,0,2.151089,33.127691,DET1;TRIM72;FBH1;UBE2D3;CCAR1;ANKRD9;HERC3;RNF...,66,4.127111
61,GO_Biological_Process_2023,Peptidyl-Serine Modification (GO:0018209),38/166,2.324139e-07,7.756813e-05,0,0,2.867133,43.794728,GSK3B;SMG1;CAMK2D;CAB39;ROCK1;TNKS;MAST2;RPS6K...,38,4.110317
62,GO_Biological_Process_2023,Insulin Receptor Signaling Pathway (GO:0008286),17/47,6.585719e-07,2.028908e-04,0,0,5.441144,77.444851,GSK3B;INSR;GAB1;SORBS1;BAIAP2;FOXO1;IGF1R;GRB1...,17,3.692738
63,GO_Biological_Process_2023,Heart Morphogenesis (GO:0003007),19/59,1.156443e-06,3.308253e-04,0,0,4.563285,62.380838,ACVR1;MYBPC3;SMAD2;RYR2;TGFB2;INSR;CHD7;TGFBR1...,19,3.480401
64,GO_Biological_Process_2023,Heart Development (GO:0007507),37/171,1.441877e-06,3.849812e-04,0,0,2.664359,35.834475,POPDC3;BMPR2;CITED2;TCF25;CHD7;PTEN;LDB3;CACNA...,37,3.414561
65,GO_Biological_Process_2023,Cardiac Myofibril Assembly (GO:0055003),9/15,1.812113e-06,4.535944e-04,0,0,14.361111,189.868498,FHOD3;CSRP3;ADPRHL1;NEBL;NRAP;TCAP;NEB;PROX1;O...,9,3.343332
66,GO_Biological_Process_2023,Negative Regulation Of DNA-templated Transcrip...,141/1025,3.631656e-06,8.555754e-04,0,0,1.562088,19.566434,RB1;ATF2;KDM1A;NAB1;ZMYND8;UBE2D3;EHMT1;UBE2D1...,141,3.067742
68,GO_Biological_Process_2023,Cellular Response To Insulin Stimulus (GO:0032...,25/99,4.086953e-06,8.614867e-04,0,0,3.249841,40.323092,GSK3B;HDAC9;FOXO1;IGF1R;GRB14;NAMPT;GRB10;PDK4...,25,3.064751
67,GO_Biological_Process_2023,Muscle Organ Development (GO:0007517),18/58,4.001169e-06,8.614867e-04,0,0,4.320813,53.703061,TRIM72;MEF2C;FHL1;TCF12;NEB;CHD2;SMTN;SGCD;ITG...,18,3.064751
69,GO_Biological_Process_2023,Protein K63-linked Deubiquitination (GO:0070536),13/33,4.537488e-06,9.086320e-04,0,0,6.231522,76.667266,OTUD4;USP13;USP25;ZRANB1;USP20;USP9X;USP33;OTU...,13,3.041612
70,GO_Biological_Process_2023,Regulation Of Intracellular Signal Transductio...,53/297,5.106164e-06,9.738185e-04,0,0,2.101178,25.602984,TRIO;FAM13B;FAM13A;ARAF;PTEN;ARHGAP5;ARHGAP35;...,53,3.011522
71,GO_Biological_Process_2023,Regulation Of Cell-Matrix Adhesion (GO:0001952),19/65,5.851258e-06,1.065195e-03,0,0,3.966755,47.794856,GSK3B;MACF1;CSF1;ROCK1;JUP;LIMCH1;PIK3CB;EFNA5...,19,2.972571
72,GO_Biological_Process_2023,Regulation Of Cell-Substrate Junction Assembly...,10/21,7.684868e-06,1.338169e-03,0,0,8.705905,102.522978,MACF1;ROCK1;LIMCH1;PEAK1;PTPRA;FYN;EFNA5;TLN1;...,10,2.873489
73,GO_Biological_Process_2023,Transmembrane Receptor Protein Serine/Threonin...,29/130,1.025461e-05,1.711239e-03,0,0,2.763806,31.750001,ITGB1;DDX5;USP15;BMPR2;ITGB5;ZFYVE9;MAP3K7;RNF...,29,2.766689
74,GO_Biological_Process_2023,Regulation Of Cardiac Muscle Cell Contraction ...,11/26,1.101162e-05,1.716902e-03,0,0,7.024929,80.200525,RYR2;CAMK2D;PLN;JUP;PDE4D;PDE4B;PKP2;CTNNA3;AN...,11,2.765254
75,GO_Biological_Process_2023,Negative Regulation Of Nucleic Acid-Templated ...,72/456,1.146068e-05,1.716902e-03,0,0,1.818247,20.685449,RB1;EIF4A2;CREBZF;KDM1A;THRA;CITED2;NAB1;BHLHE...,72,2.765254
76,GO_Biological_Process_2023,Regulation Of Nuclear-Transcribed mRNA poly(A)...,8/14,1.157462e-05,1.716902e-03,0,0,12.758681,145.024049,TNRC6C;CNOT7;CNOT1;TENT4A;CPEB3;TENT4B;TNRC6A;...,8,2.765254
77,GO_Biological_Process_2023,Regulation Of Cellular Catabolic Process (GO:0...,18/63,1.451410e-05,2.076035e-03,0,0,3.839660,42.775306,USP13;UVRAG;MTMR3;ROCK1;DAPK1;USP33;DAPK2;ITPR...,18,2.682765
78,GO_Biological_Process_2023,Protein K48-linked Ubiquitination (GO:0070936),19/70,1.899231e-05,2.622904e-03,0,0,3.576867,38.885824,UBE3C;UBE2D3;MYCBP2;UBE2E1;CUL1;UBE2D1;UBE2E2;...,19,2.581218
79,GO_Biological_Process_2023,Ventricular Cardiac Muscle Tissue Morphogenesi...,12/33,2.751757e-05,3.673595e-03,0,0,5.475055,57.491832,MYBPC3;FKBP1A;TGFBR3;RYR2;TGFB2;TNNT2;PKP2;PRO...,12,2.434909

KEGG_2019_Mouse

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,n_genes,-log10(adjusted P-value)
4055,KEGG_2019_Mouse,Adherens junction,22/72,4.719499e-07,0.000132,0,0,4.231454,61.637028,SMAD2;YES1;INSR;PTPRM;LMO7;WASL;IQGAP1;SORBS1;...,22,3.880500
4056,KEGG_2019_Mouse,Circadian rhythm,13/30,1.245072e-06,0.000174,0,0,7.332418,99.693886,PRKAB2;PRKAA2;FBXW11;BHLHE41;CUL1;RORA;CSNK1D;...,13,3.760231
4057,KEGG_2019_Mouse,Renal cell carcinoma,20/68,3.011606e-06,0.000245,0,0,4.003238,50.893307,EGLN1;TGFB2;JUN;ARAF;GAB1;ARNT;PTPN11;PIK3CB;H...,20,3.610940
4058,KEGG_2019_Mouse,Autophagy,30/130,3.511684e-06,0.000245,0,0,2.889406,36.289250,RAB7;MTMR3;PRKAA2;ITPR1;PTEN;PIK3CB;AMBRA1;HIF...,30,3.610940
4059,KEGG_2019_Mouse,Proteoglycans in cancer,40/203,6.468514e-06,0.000361,0,0,2.367920,28.293244,ITGB1;DDX5;CAMK2D;ITGB5;ROCK1;ARAF;ITPR1;ITPR2...,40,3.442561
4060,KEGG_2019_Mouse,Focal adhesion,39/199,9.587295e-06,0.000363,0,0,2.351139,27.167581,ITGB1;GSK3B;ITGB5;ROCK1;PTEN;PIK3CB;LAMC1;ARHG...,39,3.440110
4061,KEGG_2019_Mouse,Insulin resistance,26/110,9.718278e-06,0.000363,0,0,2.977411,34.363793,GSK3B;PRKAA2;PTEN;PPP1R3A;PYGM;PIK3CB;ACACB;FO...,26,3.440110
4062,KEGG_2019_Mouse,Axon guidance,36/180,1.304647e-05,0.000363,0,0,2.409689,27.101752,SEMA5A;ITGB1;GSK3B;CAMK2D;BMPR2;ROCK1;LRRC4;PI...,36,3.440110
4063,KEGG_2019_Mouse,Regulation of actin cytoskeleton,41/217,1.445321e-05,0.000363,0,0,2.247422,25.046607,CHRM2;ITGB1;CYFIP1;NCKAP1;ITGB5;ROCK1;ARAF;IQG...,41,3.440110
4064,KEGG_2019_Mouse,Insulin signaling pathway,30/139,1.449639e-05,0.000363,0,0,2.649506,29.519765,GSK3B;PRKAA2;ARAF;CBLB;PPP1R3A;PYGM;PIK3CB;ACA...,30,3.440110
4065,KEGG_2019_Mouse,Tight junction,34/167,1.514845e-05,0.000363,0,0,2.462908,27.332397,ITGB1;PRKAA2;ROCK1;NEDD4L;PPP2R2A;WASL;ACTR3B;...,34,3.440110
4066,KEGG_2019_Mouse,AMPK signaling pathway,28/126,1.561229e-05,0.000363,0,0,2.749179,30.426409,PRKAA2;CAB39;CAB39L;PPP2R2A;PIK3CB;ACACB;FOXO1...,28,3.440110
4067,KEGG_2019_Mouse,MAPK signaling pathway,50/294,3.527127e-05,0.000757,0,0,1.979027,20.289861,ATF2;CSF1;ARAF;DUSP16;IGF1R;RPS6KA3;RPS6KA2;MA...,50,3.120918
4068,KEGG_2019_Mouse,T cell receptor signaling pathway,23/101,5.810113e-05,0.001158,0,0,2.832875,27.629956,GSK3B;JUN;CHUK;PDPK1;NFATC3;NFATC2;CBLB;PIK3CB...,23,2.936339
4069,KEGG_2019_Mouse,Longevity regulating pathway,23/102,6.836573e-05,0.001272,0,0,2.796861,26.823684,ATF2;PRKAB2;PRKAA2;INSR;EHMT1;PIK3CB;ATG13;FOX...,23,2.895649
4070,KEGG_2019_Mouse,GnRH signaling pathway,21/90,8.261480e-05,0.001441,0,0,2.922258,27.473085,MAP3K2;MAP2K4;MAP3K3;CAMK2D;JUN;PLA2G4E;ITPR1;...,21,2.841458
4071,KEGG_2019_Mouse,ErbB signaling pathway,20/84,8.959716e-05,0.001470,0,0,2.999767,27.958391,GSK3B;MAP2K4;CAMK2D;JUN;ARAF;GAB1;CBLB;PIK3CB;...,20,2.832550
4072,KEGG_2019_Mouse,Salmonella infection,19/78,9.604989e-05,0.001489,0,0,3.090498,28.589090,DYNC1I2;DYNC1H1;RAB7;JUN;ROCK1;IFNGR2;WASL;KLC...,19,2.827171
4073,KEGG_2019_Mouse,Phosphatidylinositol signaling system,22/98,1.045556e-04,0.001528,0,0,2.779842,25.479451,MTMR1;DGKD;MTMR3;SACM1L;ITPR1;PTEN;ITPR2;SYNJ2...,22,2.815928
4074,KEGG_2019_Mouse,mTOR signaling pathway,30/154,1.095212e-04,0.001528,0,0,2.327059,21.221368,GSK3B;PRKAA2;CAB39;CAB39L;MAPKAP1;PTEN;PIK3CB;...,30,2.815928
4075,KEGG_2019_Mouse,Choline metabolism in cancer,22/99,1.225422e-04,0.001628,0,0,2.743588,24.711647,SLC22A4;JUN;DGKD;CHKA;PLA2G4E;PDPK1;PIK3CB;WAS...,22,2.788329
4076,KEGG_2019_Mouse,Neurotrophin signaling pathway,25/121,1.520768e-04,0.001929,0,0,2.502029,21.995648,GSK3B;CAMK2D;PIK3CB;RAP1B;CDC42;RPS6KA3;RAP1A;...,25,2.714755
4077,KEGG_2019_Mouse,Pancreatic cancer,18/75,1.778894e-04,0.002158,0,0,3.029296,26.155995,RB1;SMAD2;RALBP1;TGFB2;CHUK;ARAF;PIK3CB;PLD1;T...,18,2.665974
4078,KEGG_2019_Mouse,Ubiquitin mediated proteolysis,27/138,2.192134e-04,0.002548,0,0,2.337578,19.695181,DET1;UBE3C;UBE2D3;CUL1;UBE2D1;NEDD4L;CBLB;UBE2...,27,2.593740
4079,KEGG_2019_Mouse,Lysine degradation,15/59,3.084212e-04,0.003329,0,0,3.267407,26.413865,SETD3;KMT2A;SETDB1;KMT2C;SETD7;EHMT1;DLST;PRDM...,15,2.477658
4080,KEGG_2019_Mouse,Hepatitis B,30/163,3.102497e-04,0.003329,0,0,2.168503,17.517457,RB1;ATF2;ARAF;PIK3CB;YWHAQ;EP300;PTK2B;JAK2;MA...,30,2.477658
4081,KEGG_2019_Mouse,Arrhythmogenic right ventricular cardiomyopath...,17/72,3.281552e-04,0.003391,0,0,2.963791,23.775602,ITGB1;RYR2;ITGB5;JUP;ACTN2;CACNA2D1;CACNA1C;SG...,17,2.469680
4082,KEGG_2019_Mouse,Glucagon signaling pathway,21/102,5.215297e-04,0.005197,0,0,2.487674,18.803692,ATF2;PRKAB2;CPT1A;CAMK2D;PRKAA2;ITPR1;ITPR2;PH...,21,2.284275
4083,KEGG_2019_Mouse,Prostate cancer,20/97,6.869754e-04,0.006609,0,0,2.491516,18.146239,RB1;GSK3B;CHUK;PDPK1;ARAF;PTEN;PIK3CB;FOXO1;NF...,20,2.179853
4084,KEGG_2019_Mouse,TGF-beta signaling pathway,19/91,7.874232e-04,0.007323,0,0,2.530666,18.086027,ACVR1;SMAD2;SMAD1;TGFB2;BMPR2;ROCK1;SMURF2;ZFY...,19,2.135309

Reactome_2022

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,n_genes,-log10(adjusted P-value)
4334,Reactome_2022,Signaling By Rho GTPases R-HSA-194315,124/644,1.053811e-14,7.040720e-12,0,0,2.361911,76.015226,ITSN2;CYFIP1;NCKAP1;TRIO;FAM13B;KDM1A;WIPF3;FA...,124,11.152383
4335,Reactome_2022,"Signaling By Rho GTPases, Miro GTPases And RHO...",126/660,1.233284e-14,7.040720e-12,0,0,2.337858,74.873439,ITSN2;CYFIP1;NCKAP1;TRIO;FAM13B;KDM1A;WIPF3;FA...,126,11.152383
4336,Reactome_2022,RHO GTPase Cycle R-HSA-9012999,95/441,1.468857e-14,7.040720e-12,0,0,2.702288,86.072489,ITSN2;ITGB1;CYFIP1;NCKAP1;DOCK4;TRIO;ABCD3;FAM...,95,11.152383
4337,Reactome_2022,Signal Transduction R-HSA-162582,335/2465,9.878450e-13,3.551303e-10,0,0,1.606056,44.396596,ITSN2;NCKAP1;CYFIP1;TRIO;ZFYVE9;WIPF3;SERPINE1...,335,9.449612
4338,Reactome_2022,RAC1 GTPase Cycle R-HSA-9013149,48/178,1.568700e-11,4.511581e-09,0,0,3.584790,89.183081,ITGB1;CYFIP1;NCKAP1;DOCK4;TRIO;FAM13B;FAM13A;W...,48,8.345671
4339,Reactome_2022,Circadian Clock R-HSA-400253,24/69,8.418702e-09,1.746493e-06,0,0,5.135929,95.491351,CPT1A;MEF2C;CRTC3;CHD9;NCOA6;SERPINE1;BHLHE41;...,24,5.757833
4340,Reactome_2022,Diseases Of Signal Transduction By Growth Fact...,78/424,8.501704e-09,1.746493e-06,0,0,2.198008,40.845578,GSK3B;HIP1;ZFYVE9;ARAF;PTEN;GCC2;PIK3CB;TENT4A...,78,5.757833
4341,Reactome_2022,RAC3 GTPase Cycle R-HSA-9013423,27/93,8.010742e-08,1.439931e-05,0,0,3.941215,64.399049,ITGB1;CYFIP1;NCKAP1;TRIO;SNAP23;ARHGAP5;ARHGAP...,27,4.841658
4342,Reactome_2022,RHOC GTPase Cycle R-HSA-9013106,23/73,1.394538e-07,2.228161e-05,0,0,4.426151,69.869158,STARD13;ABCD3;ARHGEF12;ROCK1;JUP;ERBIN;MACO1;M...,23,4.652053
4343,Reactome_2022,RHOQ GTPase Cycle R-HSA-9013406,20/59,2.364623e-07,3.285072e-05,0,0,4.929518,75.212006,JUP;SNAP23;WASL;IQGAP1;CDC42BPB;ARHGAP5;ARHGAP...,20,4.483455
4344,Reactome_2022,RHOA GTPase Cycle R-HSA-8980692,35/147,2.512920e-07,3.285072e-05,0,0,3.015860,45.830965,TRIO;ABCD3;ROCK1;FAM13A;SNAP23;IQGAP1;ARHGAP5;...,35,4.483455
4345,Reactome_2022,Fcgamma Receptor (FCGR) Dependent Phagocytosis...,25/87,2.982637e-07,3.574193e-05,0,0,3.881425,58.319527,CYFIP1;NCKAP1;WIPF3;ITPR1;ITPR2;PIK3CB;WASL;CD...,25,4.446822
4346,Reactome_2022,Adaptive Immune System R-HSA-1280218,111/733,4.589325e-07,5.076499e-05,0,0,1.744543,25.460492,UBE3C;UBE2D3;UBE2D1;CBLB;NPEPPS;RNF115;HERC3;H...,111,4.294436
4347,Reactome_2022,RAC2 GTPase Cycle R-HSA-9013404,24/87,1.159549e-06,1.191022e-04,0,0,3.664863,50.089447,ITGB1;CYFIP1;NCKAP1;DOCK4;TRIO;SWAP70;ERBIN;IQ...,24,3.924080
4348,Reactome_2022,RHO GTPase Effectors R-HSA-195258,51/269,1.247064e-06,1.195518e-04,0,0,2.263873,30.776719,ITGB1;CYFIP1;NCKAP1;AHCTF1;KDM1A;WIPF3;WASL;YW...,51,3.922444
4349,Reactome_2022,Class I MHC Mediated Antigen Processing And Pr...,65/378,1.737776e-06,1.561826e-04,0,0,2.014173,26.713786,DET1;UBE3C;ITGB5;UBE2D3;SNAP23;UBE2D1;CBLB;NPE...,65,3.806367
4350,Reactome_2022,Antigen Processing: Ubiquitination And Proteas...,55/307,3.020901e-06,2.447841e-04,0,0,2.112590,26.850919,DET1;UBE3C;UBE2D3;UBE2D1;CBLB;NPEPPS;HERC3;RNF...,55,3.611217
4351,Reactome_2022,CDC42 GTPase Cycle R-HSA-9013148,33/149,3.064057e-06,2.447841e-04,0,0,2.741920,34.810785,TRIO;FAM13B;WIPF3;SNAP23;IQGAP1;WASL;ARHGAP5;A...,33,3.611217
4352,Reactome_2022,RHOB GTPase Cycle R-HSA-9013026,20/69,3.865179e-06,2.925330e-04,0,0,3.921322,48.873402,STARD13;ARHGEF12;ROCK1;JUP;SNAP23;ERBIN;MYO9B;...,20,3.533825
4353,Reactome_2022,VEGFA-VEGFR2 Pathway R-HSA-4420097,24/93,4.209698e-06,3.026773e-04,0,0,3.345067,41.405635,CYFIP1;NCKAP1;ROCK1;JUP;PDPK1;MAPKAP1;ITPR1;IT...,24,3.519020
4354,Reactome_2022,Signaling By TGFB Family Members R-HSA-9006936,28/119,4.929275e-06,3.375380e-04,0,0,2.961806,36.194209,ITGB1;USP15;CCNT2;BMPR2;ITGB5;ZFYVE9;SERPINE1;...,28,3.471677
4355,Reactome_2022,Chromatin Modifying Enzymes R-HSA-3247509,45/238,5.545630e-06,3.624825e-04,0,0,2.252125,27.256348,KDM5B;SETD3;KDM3B;MEAF6;KDM1A;KMT2A;KMT2C;SETD...,45,3.440713
4356,Reactome_2022,RHOJ GTPase Cycle R-HSA-9013409,17/54,5.942912e-06,3.715612e-04,0,0,4.410030,53.067259,TRIO;JUP;SNAP23;WASL;CDC42BPB;ARHGAP5;ARHGAP26...,17,3.429970
4357,Reactome_2022,FCGR3A-mediated Phagocytosis R-HSA-9664422,18/60,6.839019e-06,4.066400e-04,0,0,4.114605,48.934443,ACTR3;CYFIP1;NCKAP1;ACTR2;YES1;SYK;WIPF3;MYO9B...,18,3.390790
4358,Reactome_2022,RHOU GTPase Cycle R-HSA-9013420,14/39,7.069541e-06,4.066400e-04,0,0,5.370058,63.687362,ITSN2;USP9X;TXNL1;IQGAP1;CDC42;PEAK1;PTK2B;GRB...,14,3.390790
4359,Reactome_2022,Signaling By TGF-beta Receptor Complex R-HSA-1...,23/91,9.643007e-06,5.333325e-04,0,0,3.251278,37.549909,ITGB1;SMAD2;WWTR1;USP15;TGFB2;CCNT2;ITGB5;SMUR...,23,3.273002
4360,Reactome_2022,Regulation Of Actin Dynamics For Phagocytic Cu...,18/62,1.136818e-05,6.054609e-04,0,0,3.927142,44.709306,ACTR3;CYFIP1;NCKAP1;ACTR2;SYK;WIPF3;MYO9B;WASL...,18,3.217914
4362,Reactome_2022,Regulation Of MECP2 Expression And Activity R-...,12/31,1.310493e-05,6.498238e-04,0,0,6.052046,68.040259,MECP2;TNRC6C;MOV10;CAMK2D;CREB1;TBL1XR1;GPS2;T...,12,3.187204
4361,Reactome_2022,Nephrin Family Interactions R-HSA-373753,10/22,1.288920e-05,6.498238e-04,0,0,7.979972,89.847464,PIK3CA;ACTN2;MAGI2;FYN;IQGAP1;PIK3CB;WASL;SPTA...,10,3.187204
4363,Reactome_2022,RHO GTPases Activate WASPs And WAVEs R-HSA-566...,13/36,1.393662e-05,6.680286e-04,0,0,5.417815,60.576545,ACTR3;CYFIP1;NCKAP1;ACTR2;WIPF3;WASL;BAIAP2;CD...,13,3.175205